
package com.sify.network.assets.ciena;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HuwaeiU2000WebServices", targetNamespace = "http://u2000.huwaei.assets.network.sify.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HuwaeiU2000WebServices {


    /**
     * 
     * @param ason
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getOriginalRouteRequest", output = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getOriginalRouteResponse")
    public String getOriginalRoute(
        @WebParam(name = "ason", partName = "ason")
        String ason);

    /**
     * 
     * @param ason
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getRouteRequest", output = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getRouteResponse")
    public String getRoute(
        @WebParam(name = "ason", partName = "ason")
        String ason);

    /**
     * 
     * @param ason
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getRouteTopologicalLinkRequest", output = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getRouteTopologicalLinkResponse")
    public String getRouteTopologicalLink(
        @WebParam(name = "ason", partName = "ason")
        String ason);

    /**
     * 
     * @param elementid
     * @param portgroupname
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getCurrentWorkingChannelRequest", output = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getCurrentWorkingChannelResponse")
    public String getCurrentWorkingChannel(
        @WebParam(name = "portgroupname", partName = "portgroupname")
        String portgroupname,
        @WebParam(name = "elementid", partName = "elementid")
        String elementid);

    /**
     * 
     * @param customerId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getAllEmsActiveAlarmsRequest", output = "http://u2000.huwaei.assets.network.sify.com/HuwaeiU2000WebServices/getAllEmsActiveAlarmsResponse")
    public String getAllEmsActiveAlarms(
        @WebParam(name = "customerId", partName = "customerId")
        String customerId);

}
